config/routes.rb
Rails.application.routes.draw do
  resources :orders
  post 'create_review', to: 'food_items#create_review', as: 'create_review'
  post 'add_to_cart/:id', to: 'home#add_to_cart', as: 'add_to_cart'
  get 'create_order/:id', to: 'home#create_order', as: 'create_order'
  get 'food_items/:id', to: 'food_items#show', as: 'food_item'
  get 'thank_you', to: 'home#thank_you'
  root 'home#menu'
  get 'contact', to: 'home#contact'
  get 'section/:id', to: 'sections#show', as: 'section'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :food_items
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  belongs_to :cuisine
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  has_many :reviews

  scope :in_array, -> (food_items) { where(id: food_items) }
  scope :in_section, -> (section_id) { where("section_id = ?", section_id) if section_id.present?}
  scope :search, -> (s) { where("name ILIKE ?", "%#{s}%") if s.present?}
  scope :cuisine, -> (slug) { joins(:cuisine).where('cuisines.slug = ?', slug) if slug.present? }
  scope :custom_order, -> (orderValue) { 
    if orderValue.present?
      attribute, type = orderValue.split('-')
      order("#{attribute} #{type.upcase}")
    else 
      order("name ASC")
    end
  }
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :food_items, through: :order_items
  accepts_nested_attributes_for :food_items, :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :food_item
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food_item
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def show
    @food_item = FoodItem.find(params[:id])

    @food_item.view += 1

    @food_item.save!
    @average_rate = @food_item.reviews.average(:point)
    # review form
    @review = @food_item.reviews.build
  end

  # POST /create_review
  def create_review
    @review = Review.new(review_params)

    if @review.save
      redirect_to food_item_path(id: @review.food_item_id), notice: 'Thank you for giving reviews!' 
    else 
      render :show
    end
  end

  private
    def review_params
      params.require(:review).permit(:point, :name, :comment, :food_item_id)  
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def menu
    @sections = Section.all
    @order_text = { 'price-asc': 'Price low to high', 'price-desc': 'Price high to low', 'view-desc': 'Most Viewed' }
    @cuisines = Cuisine.all
    @selected_cuisine = Cuisine.where(slug: params[:cuisine]).first

    # @selected_params = params.select { |k, v| ['section_id', 'order', 's', 'cuisine'].include?(k) }
    @selected_params = params.permit(:section_id, :order, :s, :cuisine)

    order_query = { 'price-asc': "price ASC", 'price-desc': "price DESC" }

    # query
    if params[:section_id].present? || params[:s].present? || params[:cuisine].present?
      @food_items = FoodItem.in_section(params[:section_id]).search(params[:s]).cuisine(params[:cuisine]).custom_order(params[:order])
    else
      @food_items = FoodItem.all.custom_order(params[:order])
    end
  end

  def contact
  end

  def add_to_cart
    if params[:id]
      if session[:cart]
        carts = session[:cart].split(',')
      else 
        carts = []
      end
      carts.push(params[:id])
      session[:cart] = carts.join(',')

      redirect_to root_path, notice: 'You have put something in the cart'
    else
      redirect_to root_path
    end

  end

  def create_order
    @food_item = FoodItem.find(params[:id])
  end

  def thank_you
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    # @food_item = FoodItem.find(params[:food_item])

    foods = session[:cart].split(',')
    @food_items = FoodItem.in_array(foods)
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @food_items = FoodItem.in_array(params[:food_item_ids].to_a)

    # render :show

    respond_to do |format|
      result = false

      # calculate price
      # food_item = FoodItem.find(params[:food_item_id])
      @order.price = 0
      @food_items.each do |item|
        @order.price += item.price
      end
      @order.price += 20000 # delivery
      @order.price_total = @order.price

      # discount
      if params[:coupon].present? && params[:coupon] == 'CODERSCHOOL'
        @order.price_total *= 0.5
      end

      #save
      if params[:food_item_ids].present?
        Order.transaction do
          @order.save!
          @food_items.each do |item|
            @order.order_items.create({ food_item_id: item.id }).save!
          end
        end
        session[:cart] = ''
        format.html { redirect_to thank_you_path(id: @order.id), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end

      # if @order.save
      #   format.html { redirect_to @order, notice: 'Order was successfully created.' }
      #   format.json { render :show, status: :created, location: @order }
      # else
      #   format.html { render :new }
      #   format.json { render json: @order.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :age, :phone, :email)
    end

    def food_item_params
      params.require(:order_item).permit(:food_item_id)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @section = Section.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/food_items/_food_item.html.erb
<div class="food-item">
  <div class="food-item-thumb" style="background-image: url(<%= image_url(food_item.url) %>)">
    <div class="overlay">
      <%= link_to "Add to cart", add_to_cart_path(food_item.id), class: "btn btn-primary", :method => :post %>
      <%= link_to "View", food_item_path(food_item), class: "btn btn-default" %>
    </div>
  </div>
  <p class="food-item-name"><%= link_to food_item.name, food_item_path(food_item) %></p>
  <p class="food-item-price"><%= number_to_currency(food_item.price, precision: 0, unit: 'đ') %></p>
  <p class="food-item-viewed"><small>Viewed <%= pluralize(food_item.view, 'time') %></small></p>
</div>

app/views/food_items/_review.html.erb
<div class="review-item">
  <div class="review-author">
    <strong><%= review.name %></strong> rated for <strong><%= review.point %> points</strong> and said:
  </div>
  <div class="desc">
    <p><%= review.comment %></p>
  </div>
</div>

app/views/food_items/show.html.erb
<div class="container">
  <% if notice.present? %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="single-food-thumb">
        <%= image_tag @food_item.url %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="single-food-info">
        <div class="single-food-header">
          <h1><%= @food_item.name %></h1>
          <h3 class="price"><%= number_to_currency(@food_item.price, precision: 0, unit: 'đ') %></h3>
          <% if @average_rate.present? %>
            <div class="review-stars">
              <div class="review-stars-bg">
                <%= fa_icon 'star' %>
                <%= fa_icon 'star' %>
                <%= fa_icon 'star' %>
                <%= fa_icon 'star' %>
                <%= fa_icon 'star' %>
              </div>
              <div class="review-stars-fg" style="width: <%= (@average_rate / 5 * 100).to_i %>%">
                <%= fa_icon 'star' %>
                <%= fa_icon 'star' %>
                <%= fa_icon 'star' %>
                <%= fa_icon 'star' %>
                <%= fa_icon 'star' %>
              </div>
            </div>
          <% end %>
        </div>
        <p><%= @food_item.section.name %></p>
        <div class="desc"><p><%= @food_item.description %></p></div>
        <p><em><%= @food_item.name %> has been viewed <%= pluralize(@food_item.view, 'time') %></em></p>
        <div class="mt-3">
          <%= link_to "Add to cart", add_to_cart_path(@food_item.id), class: "btn btn-primary", :method => :post %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h4 class="mt-4">Give Reviews</h4>
      <%= form_for @review, url: create_review_path(@review) do |review| %>
        <%= review.hidden_field :food_item_id, value: @food_item.id  %>
        <div class="form-group">
          <%= review.label :name %>
          <%= review.text_field :name, value: @review.name.present? ? @review.name : Faker::Name.name , class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= review.label :point %>
          <%= review.number_field :point, value: @review.point.present? ? @review.point : 5 , class: 'form-control',  :min => 1, :max => 5, maxlength: 1 %>
        </div>
        <div class="form-group">
          <%= review.label :comment %>
          <%= review.text_area :comment, value: @review.comment.present? ? @review.comment : Faker::Lorem.paragraph, class: 'form-control', rows: 8 %>
        </div>
        <div class="form-group text-center">
          <button type="submit" class="btn btn-primary">Give Review</button>
        </div>
      <% end %>

      <% if @food_item.reviews.count > 0 %>
        <h4 class="mt-4"><%= @food_item.reviews.count %> Reviews</h4>
        <% @food_item.reviews.each do |review| %>
          <% if review.id.present? %>
            <%= render 'review', review: review %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_order_form.html.erb
<%= form_tag do %>
  
<% end %>

app/views/home/contact.html.erb
<div class="contact">
  <div class="container">    
    <div class="row">
      <div class="col-md-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1959.7186106670413!2d106.69643926258033!3d10.777786746982034!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x1787491df0ed8d6a!2sIndependence+Palace!5e0!3m2!1sen!2s!4v1497496548346" width="100%" height="450" frameborder="0" style="border:0"></iframe>
      </div>
      <div class="col-md-6 align-self-center">
        <div>
          <h2 class="heading">Contact us</h2>
          <p class="address-line">
            <%= fa_icon "address-book-o" %>
            135 Nam Kỳ Khởi Nghĩa, Bến Thành<br>
            Quận 1, Hồ Chí Minh<br>
            Vietnam
          </p>
          <p class="address-line"><%= fa_icon "phone", text: link_to("(84) 1234 56789", 'tel:+84123456789') %></p>
          <p class="address-line"><%= fa_icon "envelope-o", text: link_to("hello@delicious.com", 'mailto:hello@delicious.com') %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/create_order.html.erb
<div class="container">
  create order for <%= @food_item.name %>

  <%= render 'order_form', @food_item %>
</div>

app/views/home/menu.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <div class="filter-bar">
    <div class="section-list">
      <%= link_to "All", root_path, class: "#{'active' if !params[:section_id].present? }" %>
      <% @sections.each do |section| %>
        <%= link_to section.name, root_path(:section_id => section.id), class: "#{'active' if section.id.to_s == params[:section_id]}" %>
      <% end %>
    </div>
    <div class="right-bar">
      <div class="dropdown">
        <button class="btn btn-link dropdown-toggle" data-toggle="dropdown">
          <%= params[:cuisine].present? ? @selected_cuisine.name : 'All Cuisine' %>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "All Cuisine", root_path(@selected_params.except(:cuisine)), class: "dropdown-item" %>
          <% @cuisines.each do |cuisine| %>
            <%= link_to cuisine.name, root_path(@selected_params.merge(:cuisine => cuisine.slug)), class: "dropdown-item" %>
          <% end %>
        </div>
      </div>
      <div class="dropdown">
        <button class="btn btn-link dropdown-toggle" data-toggle="dropdown"><%= params[:order].present? ? @order_text[params[:order].to_sym] : 'Alphabetical' %></button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "Alphabetical", root_path(@selected_params.except(:order)), class: "dropdown-item" %>
          <% @order_text.each do |key, value| %>
            <%= link_to value, root_path(@selected_params.merge(:order => key)), class: "dropdown-item" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="menu-list row">
    <%= render @food_items %>
  </div>
</div>

app/views/home/thank_you.html.erb
<div class="container">
  <% if notice.present? %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>
  
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1>Thank you for your order!</h1>

      <h3 class="heading__form">Items</h3>
      <table class="table">
        <thead>
          <tr>
            <th>Item</th>
            <th class="text-right">Price</th>
          </tr>
        </thead>
        <tbody>
          <% @order.food_items.each do |item| %>
            <%= render 'orders/cart_item', food_item: item %>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td>Delivery</td>
            <td class="text-right"><span class="price"><%= number_to_currency(20000, precision: 0, unit: 'đ') %></span></td>
          </tr>
          <tr>
            <td>Sum</td>
            <td class="text-right"><span class="price"><%= number_to_currency(@order.price, precision: 0, unit: 'đ') %></span></td>
          </tr>
          <% if @order.price != @order.price_total %>
          <tr>
            <td>Discount</td>
            <td class="text-right"><span class="price text-success"><%= number_to_currency(@order.price - @order.price_total, precision: 0, unit: 'đ') %></span></td>
          </tr>
          <% end %>
          <tr>
            <td><strong>Total</strong></td>
            <td class="text-right"><strong><span class="price"><%= number_to_currency(@order.price_total, precision: 0, unit: 'đ') %></span></strong></td>
          </tr>
        </tfoot>
      </table>
      

      <h3 class="heading__form">Order Information</h3>
      <table class="table table-striped table-blank">
        <tbody>
          <tr>
            <td class="th">Date</td>
            <td class="text-right"><%= @order.created_at.to_formatted_s(:long) %></td>
          </tr>
          <tr>
            <td class="th">Contact Name</td>
            <td class="text-right"><%= @order.name %></td>
          </tr>
          <tr>
            <td class="th">Phone</td>
            <td class="text-right"><%= @order.phone %></td>
          </tr>
          <tr>
            <td class="th">Email</td>
            <td class="text-right"><%= @order.email %></td>
          </tr>
        </tbody>
      </table>
      <p><%= link_to "Go to Menu", root_path %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delicious</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Delicious", root_path, :class => 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Menu', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact Us', contact_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Checkout', new_order_path, class: 'nav-link' %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <%= hidden_field_tag 'order', params[:order] %>
          <%= hidden_field_tag 'section_id', params[:section_id] %>
          <input class="form-control mr-sm-2" type="text" name="s" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/orders/_cart_item.html.erb
<tr>
  <td><%= link_to food_item.name, food_item_path(food_item.id) %></td>
  <td class="text-right"><span class="price"><%= number_to_currency(food_item.price, precision: 0, unit: 'đ') %></span></td>
</tr>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% food_items.each do |item| %>
    <%= hidden_field_tag 'food_item_ids[]', item.id %>
  <% end %>

  <div class="form-group">
    <label>Your Name</label>
    <%= text_field(:order, :name, class: 'form-control', :value => Faker::Name.name) %>
  </div>
  <div class="form-group">
    <label>Your Phone</label>
    <%= text_field(:order, :phone, class: 'form-control', :value => Faker::PhoneNumber.cell_phone) %>
  </div>
  <div class="form-group">
    <label>Your Email</label>
    <%= text_field(:order, :email, class: 'form-control', :value => Faker::Internet.email) %>
  </div>

  <div class="form-group">
    <label>Coupon</label>
    <%= text_field_tag 'coupon', '', class: 'form-control', placeholder: "Enter your coupon" %>
  </div>

  <div class="actions text-center">
    <button type="submit" class="btn btn-primary" role="button">Create</button>
    <%= link_to 'Cancel', root_path, class: "btn btn-link text-danger" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="container container__first">
  <h1 class="text-center">Place New Order</h1>
  <div class="row">
    <div class="col-md-6">
      <h3 class="heading__form">Items</h3>
      <table class="table">
        <thead>
          <tr>
            <th>Item</th>
            <th class="text-right">Price</th>
          </tr>
        </thead>
        <tbody>
          <% @food_items.each do |food_item| %>
            <%= render 'cart_item', food_item: food_item %>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td>Delivery</td>
            <td class="text-right"><span class="price">$20,000</td>
          </tr>
          <tr>
            <td><strong>Total</strong></td>
            <td class="text-right"><span class="price"><%= number_to_currency(@food_items.map{|item| item.price}.sum + 20000, precision: 0, unit: 'đ') %></span></td>
          </tr>
        </tfoot>
      </table>
    </div>
    <div class="col-md-6">
      <h3 class="heading__form">Order Information</h3>
      <%= render 'form', order: @order, food_items: @food_items %>
    </div>
  </div>
</div>
<% debug session[:cart] %>
<% debug @food_items %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<% @food_items.each do |item| %>
  <%= item.name %>
<% end %>

<%= debug @food_items %>

app/views/sections/_section.html.erb
<a href="<%= section_url(section) %>">
  <div class="section-card section-card-<%= section.slug %>" style="background-image: url(<%= image_url(section.slug) %>)">
    <h4><%= section.name %></h4>
  </div>
</a>

app/views/sections/show.html.erb
<div class="container">
  <h1><%= @section.name %></h1>

  <h2>List</h2>
  <ul>
    <% @section.food_items.each do |food| %>
    <li>
      <p><%= image_tag food.url.to_s %></p>
      <p>Name: <%= food.name %></p>
    </li>
    <% end %>
  </ul>
</div>